#!/bin/bash

Year=`date +%Y`
Month=`date +%m`
Day=`date +%d`
Hour=`date +%H`
Minute=`date +%M`
Second=`date +%S`
echo `date`
echo "jelenlegi dátum: $Year-$Month-$Day"
echo "Jelenlegi idő: $Hour:$Minute:$Second"
